spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://licalhost:5432/dev_db
          username: postgres
          password: Qwerty1
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://licalhost:5432/prod_db
    username: postgres
    password: Qwerty1